name: Deploy to Supabase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Supabase CLI
      run: |
        curl -fsSL https://supabase.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Supabase CLI
      run: supabase --version

    - name: Deploy Functions
      run: |
        supabase functions deploy --project-ref $PROJECT_ID --token $ACCESS_TOKEN
      env:
        PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
