name: Deploy to Supabase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: |
        wget -O supabase.tar.gz https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz
        tar -xzf supabase.tar.gz
        sudo mv supabase /usr/local/bin/
        chmod +x /usr/local/bin/supabase

    - name: Verify Installation
      run: supabase --version

    - name: Deploy Functions
      run: |
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
